### ISSUE TITLE
About the version of pytorch

### ISSUE THREAD

**Issue by zengchen233** [emirozturk/MLMStego#1]
Dear emirozturk:
         Hello, I have a question about the version of torch, if I want to rerun your code, Can I use the torch<=2.0?

**Comment by emirozturk** [comment]
Yes. It works in older versions

**Comment by zengchen233** [comment]
> Yes. It works in older versions

okok， thank you！ If I have questions about your paper, I will open an issue to ask you. I wish you have a nice day!
